Example\Domain\Model\Employee\Employee:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  table: employees
  repositoryClass: Example\Infrastructure\Persistence\Doctrine\Employee\DoctrineEmployeeRepository
  fields:
    name:
      type: string
      unique: true
    created_at:
      type: custom_datetime
